version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis_db
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
